id: PD9CAA54A
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG11942
  instance_id: http://purl.bdrc.io/resource/IE1KG11942
  collection_id: http://purl.bdrc.io/resource/PR0ET004
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གསུང་འབུམ། ངག་དབང་ལེགས་པ། ༼གློག་ཀླད་པར་མ།༽
  alt_title: {}
  author: http://purl.bdrc.io/resource/P812
  publisher: GuruLamaWorks
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    344e03a335ac4cebb8be2c8abf92a72a:
      title: ༄༅།་།ན་མོ་གུ་རུ།རང་བཞིན་བརྒྱད་ཅུའི་རྟོག་པ་ལ་རིགས་གསུམ་ལས།དང་པོ་ཞེ་སྡང་གི་རྟོག་རིགས་སོ་གསུམ་ནི།ཡུལ་མི་འདོད་པའི་རྣམ་པ་ཅན་ལ་ཤས་ཆུང
      volume_number: 15
      base_file: UT1KG11942_015_0000.txt
      reference: http://purl.bdrc.io/resource/VL7C40EC9F540234AD
      image_group: null
      quality: null
    cd5e39f57c564859aa5b8e8a43d131ec:
      title: ༄༅།་།ལམ་ཟབ་ཚར་གསུམ་ཁུག་པ་རྒྱུན་ཁྱེར་ཉམས་སུ་བླང་ཚུལ་སྔགས་འཆང་དབང་པོའི་སྙིང་ནོར་ཞེས་བྱ་བ་བཞུགས་སོ།་།ལམ་ཟབ་ཚར་གསུམ་ཁུག་པའི་རྣལ་འབ
      volume_number: 10
      base_file: UT1KG11942_010_0000.txt
      reference: http://purl.bdrc.io/resource/VL7860987673C3F57A
      image_group: null
      quality: null
    045579b731434d9cb078c11bb5d55fce:
      title: ༄༅།་།བླ་མ་རྡོ་རྗེ་འཆང་གི་རྣལ་འབྱོར་སྙིང་གི་བདུད་རྩི་བཞུགས་སོ།་།ན་མོ་གུ་རུ་བཛྲ་དྷ་ར་ཡ།བློ་ལྡན་གང་ཞིག་དད་པ་མོས་གུས་ལམ་གྱི་སྲོག་ཏ
      volume_number: 6
      base_file: UT1KG11942_006_0000.txt
      reference: http://purl.bdrc.io/resource/VLA45F45B9B4A3F6FB
      image_group: null
      quality: null
    8c90534727f4468aa1454d5657e68c3f:
      title: ༄༅།་།ཆོས་སྐྱོང་སྤྱིའི་ཚོགས་འཁོར་གྱི་ཡི་གེ་བདུད་རྩིའི་སྤྲིན་ཕུང་ཞེས་བྱ་བ་བཞུགས་སོ།་།ན་མོ་གུ་རུ་མ་ཧཱ་ཀཱ་ལཱ་ཡ།གང་ཐུགས་ཆོས་ཀྱི་དབྱ
      volume_number: 19
      base_file: UT1KG11942_019_0000.txt
      reference: http://purl.bdrc.io/resource/VL3A70E222571362B4
      image_group: null
      quality: null
    a54b9a1d79a346ecb2404858782a665f:
      title: ༄༅།་།མགོན་པོ་ཡིད་བཞིན་ནོར་བུའི་འདོད་གསོལ་ཕྲིན་ལས་མྱུར་འགྲུབ་ཅེས་བྱ་བ་བཞུགས་སོ།་།ཧཱུྃ།བླ་མ་མགོན་པོ་ཡིད་བཞིན་ནོར་བུ་ལ།་།མཆོད་གཏོ
      volume_number: 18
      base_file: UT1KG11942_018_0000.txt
      reference: http://purl.bdrc.io/resource/VLA526D7C01C625D22
      image_group: null
      quality: null
    38fb8fffb0814a538e6f11ce6616eba6:
      title: ༄༅།་།ལམ་ཟབ་ནང་གི་བླ་མའི་རྣལ་འབྱོར་བཞུགས་སོ།་།ཨོཾ་སྭ་སྟི།གང་གི་དྲིན་གྱིས་ལྷན་སྐྱེས་བདེ་བ་ཆེ།་།སྐད་ཅིག་ཉིད་ལ་འཆར་བ་མཛད་པ་ཡི།་།
      volume_number: 8
      base_file: UT1KG11942_008_0000.txt
      reference: http://purl.bdrc.io/resource/VL65435461BF10EC5F
      image_group: null
      quality: null
    64aa157c39e94925a4d7ecd1b9bd9ad4:
      title: ༄༅།་།བདག་ཉིད་ཆེན་པོ་གཞུང་ལུགས་རབ་འབྱམས་པའི་བླ་མའི་རྣལ་འབྱོར་བྱིན་རླབས་ཆར་འདེབས་ཞེས་བྱ་བ་བཞུགས་སོ།་།ན་མོ་གུ་རུ་ཨ་ནནྡ་ཛྙཱ་ན་ཡ།རབ
      volume_number: 7
      base_file: UT1KG11942_007_0000.txt
      reference: http://purl.bdrc.io/resource/VLD2B13D6C9C1F30D5
      image_group: null
      quality: null
    631633ea237d48a895b2883d2aa64011:
      title: ༄༅།་།རྗེ་བླ་མ་ཀུན་དགའ་ཆོས་ལྷའི་རྣམ་ཐར་བཞུགས་སོ།་།༄༅།་།ཀུན་ཁྱབ་ཟབ་གསལ་དབྱིངས་ནས་མ་གཡོས་བཞིན།་།འགྲོ་ལ་ཕན་བདེའི་དགའ་སྟོན་སྤེལ་ས
      volume_number: 25
      base_file: UT1KG11942_025_0000.txt
      reference: http://purl.bdrc.io/resource/VLF3714C2C1745BD8F
      image_group: null
      quality: null
    ba3b151f362644789a09435e6c7bbe5c:
      title: ༄༅།་།འཇམ་དབྱངས་བླ་མའི་རྣལ་འབྱོར་ཉམས་སུ་ལེན་ཚུལ་བྱིན་རླབས་ཆར་འབེབས་ཞེས་བྱ་བ་བཞུགས་སོ།་།ན་མོ་གུ་རུ་མཉྫུ་གྷོ་ཥ་ཡ།འདིར་འཇམ་དབྱངས་བ
      volume_number: 4
      base_file: UT1KG11942_004_0000.txt
      reference: http://purl.bdrc.io/resource/VL57E1596558DEE06B
      image_group: null
      quality: null
    b6796b9abb4e47499c830a1ce3881e5a:
      title: ༄༅།་།མར་མེའི་སྨོན་ལམ་མཆོད་སྤྲིན་རྒྱ་མཚོ་བཞུགས་སོ།་།རིན་ཆེན་དང་པོའི་ཀོང་བུ་ནི།་།སྟོང་གསུམ་ཁྱོན་དང་མཉམ་པའི་ནང་།་།རྩི་མར་བཅུད་ཀ
      volume_number: 11
      base_file: UT1KG11942_011_0000.txt
      reference: http://purl.bdrc.io/resource/VLBA928B3C0C47A442
      image_group: null
      quality: null
    913b035e47c843bda09d70afba9b9c0c:
      title: ༄༅།་།རྗེ་བཙུན་བླ་མ་དམ་པའི་ཞབས་ལ་གུས་པས་ཕྱག་འཚལ་ལོ།་།བདེ་སྟོང་ཟུང་འཇུག་མཆོག་གི་དཀྱིལ་འཁོར་ལ།་།ཁ་སྦྱོར་ཡན་ལག་བདུན་གྱི་ཆ་ཤས་རྫོག
      volume_number: 14
      base_file: UT1KG11942_014_0000.txt
      reference: http://purl.bdrc.io/resource/VLF4857A1090EB6969
      image_group: null
      quality: null
    90660d2bfae84bd4b1abddb7ae92df19:
      title: ༄༅།་།རབ་འབྱམས་གཞུང་ལུགས་རྒྱ་མཚོའི་ཕ་རོལ་ཏུ་སོན་པ་མཆོག་སྤྲུལ་ཐམས་ཅད་མཁྱེན་པ་སྙན་གྲགས་ལུང་རིགས་ཉི་མ་འཇིགས་བྲལ་སྨྲ་བའི་སེངྒེ་དཔལ་བ
      volume_number: 16
      base_file: UT1KG11942_016_0000.txt
      reference: http://purl.bdrc.io/resource/VLC63354C944A3D9BC
      image_group: null
      quality: null
    0797b6f4aa59437ca474b44e80a5a22c:
      title: ༄༅།་།བྱང་ཆུབ་སེམས་དཔའི་སྨོན་ལམ་ཐེག་ཆེན་ལམ་གྱི་སྙིང་པོ་བཞུགས་སོ།་།བླ་མ་དམ་པ་རྣམས་དང་ལྷག་པའི་ལྷ་ལ་གུས་པས་ཕྱག་འཚལ་ལོ།་།རབ་འབྱམས་
      volume_number: 23
      base_file: UT1KG11942_023_0000.txt
      reference: http://purl.bdrc.io/resource/VL1F8937FF6C0A7465
      image_group: null
      quality: null
    165c6925be6745a2ab16e18ba5119368:
      title: ༄༅།་།རྗེ་བཙུན་བི་པའི་སྲུང་བའི་མན་ངག་བར་ཆད་ཀུན་སེལ་ཞེས་བྱ་བ་བཞུགས་སོ།་།རྗེ་བཙུན་བི་པའི་སྲུང་བའི་མན་ངག་བར་ཆད་ཀུན་སེལ་ཞེས་བྱ་བ།བླ
      volume_number: 9
      base_file: UT1KG11942_009_0000.txt
      reference: http://purl.bdrc.io/resource/VLADE0762CE65512D1
      image_group: null
      quality: null
    8edbc6342edc4f8885871b80d430e94d:
      title: ༄༅།་།སྒ་སྟོན་རྡོ་རྗེ་འཆང་ངག་དབང་ལེགས་པས་མཛད་པའི་དག་པ་དྲན་པའི་འགྲེལ་པ་བཞུགས་སོ།་།བླ་མ་དམ་པའི་ཞབས་ལ་ཕྱག་འཚལ་ལོ།་།མཉམ་པར་མ་བཞག་པ
      volume_number: 13
      base_file: UT1KG11942_013_0000.txt
      reference: http://purl.bdrc.io/resource/VL7A3A64D128F6B62B
      image_group: null
      quality: null
    61e46eeeeef24c3cacec122eb2e72b74:
      title: ༄༅།་།མར་མེའི་སྨོན་ལམ་མཆོད་སྤྲིན་རྒྱ་མཚོ་བཞུགས་སོ།་།རིན་ཆེན་དང་པོའི་ཀོང་བུ་ནི།་།སྟོང་གསུམ་ཁྱོན་དང་མཉམ་པའི་ནང་།་།རྩི་མར་བཅུད་ཀ
      volume_number: 21
      base_file: UT1KG11942_021_0000.txt
      reference: http://purl.bdrc.io/resource/VL474FE18B3D7FFBC0
      image_group: null
      quality: null
    74b83224b8ab45da9e20ea5cf865bc9e:
      title: ༄༅།་།གནོད་བྱེད་འབྱུང་པོའི་གསུར་བསྔོ་རྐྱེན་ངན་ཀུན་གྲོལ་བཞུགས་སོ།་།ཕྱེ་མར་ཤ་ཁྲག་སོགས་ཟས་སྣ་གང་འཛོམས།དམ་རྫས་མྱོང་གྲོལ་ཡོད་ན་བསྲེ།
      volume_number: 22
      base_file: UT1KG11942_022_0000.txt
      reference: http://purl.bdrc.io/resource/VLCFA1B708C9987BCA
      image_group: null
      quality: null
    694c26f7a41142b48f721f3570a35539:
      title: ༄༅།་།བླ་མ་རིན་ཆེན་འབྱུང་ལྡན་གྱི་རྣལ་འབྱོར་ཉམས་སུ་ལེན་ཚུལ་སྲིད་ཞིའི་དཔལ་འབྱོར་རབ་རྒྱས་ཞེས་བྱ་བ་བཞུགས་སོ།་།ན་མོ་གུ་རུ་རཏྣ་སཾ་བྷ་
      volume_number: 3
      base_file: UT1KG11942_003_0000.txt
      reference: http://purl.bdrc.io/resource/VLDB746183031998C1
      image_group: null
      quality: null
    a9752a4ba7a04a9584230621858bd051:
      title: ༄༅།་།འཁོར་འདས་དབྱེར་མེད་ཀྱི་ལྟ་བའི་སྙིང་པོ་བསྡུས་པ་སྐལ་བཟང་སྙིང་གི་བདུད་རྩི་ཞེས་བྱ་བ་བཞུགས་སོ།་།འཇམ་དབྱངས་བླ་མ་ལ་ཕྱག་འཚལ་ལོ།
      volume_number: 12
      base_file: UT1KG11942_012_0000.txt
      reference: http://purl.bdrc.io/resource/VL03EAEF1F433742DC
      image_group: null
      quality: null
    e679b55cb9874770a0a06c3bb9e5bd54:
      title: ༄༅།་།ཀ་ཅའི་བསོག་འཇོག་སྤོང་བའི་བྱ་བྲལ་ལགས།་།ཁ་རོག་མ་བཞུགས་དམ་པའི་ཆོས་ལ་རེམས།་།ག་ལེར་མ་བསམས་ནམ་འཆི་ཆ་མེད་ཡིན།་།ང་ཡི་སྙིང་གཏམ་འ
      volume_number: 2
      base_file: UT1KG11942_002_0000.txt
      reference: http://purl.bdrc.io/resource/VL926D6F4D4698777D
      image_group: null
      quality: null
    2daf4075c4e74937a8c8aa68901297a0:
      title: ༄༅།་།སྒ་སྟོན་ངག་དབང་ལེགས་པའི་གསུང་སྐོར་གྱི་དཀར་ཆག།༠༠༡སྒ་སྟོན་རྡོ་རྗེ་འཆང་འཇམ་མགོན་ངག་དབང་ལེགས་པའི་གསུང་ཐོར་བུ་ཁག༠༠༢ཀ་མད་སུམ་ཅུ་
      volume_number: 27
      base_file: UT1KG11942_027_0000.txt
      reference: http://purl.bdrc.io/resource/VL3170D4207083EE81
      image_group: null
      quality: null
    bad1f3671f3345fabc730336d728adbb:
      title: ༄༅།་།དཔལ་ཀྱེ་རྡོ་རྗེའི་ཕྱི་ནང་གི་བསྐྱེད་པའི་རིམ་པ་ལམ་དུས་ཀྱི་དབང་ལེན་པའི་སྐབས་རྣམས་སུ་ཉེ་བར་མཁོ་བའི་ཟིན་བྲིས་བཞུགས་སོ།་།རྣམ་ཐར
      volume_number: 24
      base_file: UT1KG11942_024_0000.txt
      reference: http://purl.bdrc.io/resource/VLE8CE15B08A36B291
      image_group: null
      quality: null
    03def28d265845578915f2c8cc9622d5:
      title: ༄༅།་།འཇམ་དབྱངས་བླ་མ་ས་སྐྱ་པཎྜི་ཏ་ཁྱེད་ཐུགས་དགྱེས་པའི་ཕྲིན་ལས་ཐམས་ཅད་རྗེས་སུ་བསྒྲུབ་པའི་སླད་དུ།འཇམ་དབྱངས་བླ་མ་སྐྱབས་གནས་ཀུན་འདུས
      volume_number: 5
      base_file: UT1KG11942_005_0000.txt
      reference: http://purl.bdrc.io/resource/VL5B4680E5B741EED7
      image_group: null
      quality: null
    27533acf72924ee2a4dd1245fed89f7e:
      title: ༄༅།་།སྡེ་གཞུང་སྤྲུལ་སྐུ་རིན་པོ་ཆེ་འཇམ་དབྱངས་ཀུན་དགའ་རྒྱལ་མཚན་གྱིས་འཇམ་མགོན་ལེགས་པ་རིན་པོ་ཆེར་བཀའ་འདྲི་ཞུས་ལན་ཁག་ཅིག།བླ་མ་ལ་ཕྱག་
      volume_number: 26
      base_file: UT1KG11942_026_0000.txt
      reference: http://purl.bdrc.io/resource/VL8261E9F75259C6E9
      image_group: null
      quality: null
    ef7004c4360f4465b984d68a4d2479ba:
      title: ༄༅།་།སྒ་སྟོན་རྡོ་རྗེ་འཆང་འཇམ་མགོན་ངག་དབང་ལེགས་པའི་གསུང་ཐོར་བུ་བཞུགས་སོ།་།༄༅།་།རབ་འབྱམས་པ་ཡབ་སྲས་གསུམ་གྱི་བསྟོད་པ།་།ཨོཾ་སྭ་སྟ
      volume_number: 1
      base_file: UT1KG11942_001_0000.txt
      reference: http://purl.bdrc.io/resource/VLFEBB3A6CD3271829
      image_group: null
      quality: null
    37c31d406cf24979b416c870de180b13:
      title: ༄༅།་།ཚིམ་པ་དྲུག་ལྡན་ཚོགས་ཀྱི་འཁོར་ལོའི་གླུ་གནས་གསུམ་ཌཱ་ཀི་དགྱེས་པའི་ཏཾ་བུ་ར་ཞེས་བྱ་བ་བཞུགས་སོ།་།དུས་གསུམ་སངས་རྒྱས་ཐམས་ཅད་འདུས་
      volume_number: 20
      base_file: UT1KG11942_020_0000.txt
      reference: http://purl.bdrc.io/resource/VL9995F2D42766E983
      image_group: null
      quality: null
    91e8e7d0226f497e866b092b46303832:
      title: ༄༅།་།དཔལ་ལྡན་ས་སྐྱ་པའི་བསྟན་སྲུང་དབང་པོ་རྣམས་ལ་གསེར་སྐྱེམས་འདོད་དགུའི་དཔལ་སྟེར་བཞུགས་སོ།་།ཨོཾ་སྭ་སྟི་བི་ཛ་ཡནྟུ།འདིར་དཔལ་ལྡན་ས་
      volume_number: 17
      base_file: UT1KG11942_017_0000.txt
      reference: http://purl.bdrc.io/resource/VL4906108A2F852366
      image_group: null
      quality: null
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG11942
  - http://purl.bdrc.io/resource/W1KG11942
created_at: '2021-12-24T17:08:52.655521'
last_modified_at: '2021-12-24T17:08:52.655572'
statistics:
  total_words: 57859
  total_non_words: 6684
quality:
  non_words_ratio: 0.12
